AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Code charge depuis src/main.py'

Parameters:
  Environment:
    Type: String
    Description: 'Environnement name (e.g. votre identifiant sans le learnaws)'
    Default: 'skumako'
  BucketName:
    Type: String
    Description: 'S3 bucket name (e.g. votre identifiant sans le learnaws + -bucket pour différencier du bucket de votre voisin)'
    Default: 'skumako-s3-bucket-trigger-lambda'

Resources:
# Rôle IAM pour la fonction Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:GetObject]
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*'
                # Resource: !GetAtt S3Bucket.Arn

                # Ecrire dand la base de données
              - Effect: Allow
                Action: [
                    dynamodb:PutItem,
                    dynamodb:GetItem
                ]
                Resource: 'arn:aws:dynamodb:::table/s3-trigger-db'

  # Fonction Lambda
  LambdaTigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code: ../src

  LambdaPermissionsForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTigger
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  # S3 bucket pour stocker les fichier
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaTigger.Arn