# yaml-language-server: $schema=https://s3.amazonaws.com/cfn-resource-specifications-us-east-1-prod/schemas/2.15.0/all-spec.json
AWSTemplateFormatVersion: '2010-09-09'
Description: "TP AWS Lambda - Code Chargé depuis src/main.py"

Parameters:
  Environment:
    Type: String
    Description: "Nom de l'environnement (dev, staging, prod)"
    Default: "skumako"

  BucketName:
    Type: String
    Description: "Nom du bucket S3 pour stocker le code de la fonction Lambda"
    Default: "iabd-sourcecode-management-bucket"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: !Sub "${Environment}-LambdaS3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow          # ✅ Deny → Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*'

  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-S3LambdaTrigger"
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Sub "${Environment}-lambda.zip"

  LambdaPermissionForS3:              # ✅ Ajout
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTrigger
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-${BucketName}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt LambdaTrigger.Arn