AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Code charge depuis src/main.py'
Parameters:
  Environment:
    Type: String
    Description: 'Environnement name (e.g. votre identifiant sans le learnaws)'
    Default: 'skumako'
  BucketName:
    Type: String
    Description: 'S3 bucket name'
    Default: 'skumako-s3-bucket-trigger-lambda'
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${Environment}-LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: 'arn:aws:dynamodb:*:*:table/s3-trigger-db'
  LambdaTigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.11
      Code: ../src
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaTigger.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaTigger.Arn